/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProcessValueType } from './processValueType';
import { Value } from './value';


/**
 * Represents a process value. 
 */
export interface ProcessValue { 
    name: string;
    value?: Value;
    value_unit?: string;
    value_type: ProcessValueType;
    writable: boolean;
    options?: Array<string>;
}



