/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ready } from './ready';
import { NotOnline } from './notOnline';
import { InProgress } from './inProgress';
import { ProcessUnitStateEnum } from './processUnitStateEnum';


export interface State { 
    state?: ProcessUnitStateEnum;
    progress_pct: number;
    last_seen_date: string;
}



