name: pectus
dependencies:
  - python=3.11
  - pip
  
  - pip:
    - -r openpectus/requirements.txt

# Manage conda environment
# Usually updating works:
# conda env update -n=pectus --file=environment.yml --prune

# If that does not work, remove the environment and recreate it:
# conda env remove --name pectus
# conda env create --name pectus --file=environment.yml
