"""remove is_anon and let user_id be None for webpush

Revision ID: 2f7a4893cb4d
Revises: b60f2a2cc10d
Create Date: 2025-06-16 11:21:00.839015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f7a4893cb4d'
down_revision: Union[str, None] = 'b60f2a2cc10d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WebPushNotificationPreferences', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('is_anon')

    with op.batch_alter_table('WebPushSubscriptions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WebPushSubscriptions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('WebPushNotificationPreferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anon', sa.BOOLEAN(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
