"""Introduce recent run archive

Revision ID: 7afe4ee89133
Revises: 080cfe381209
Create Date: 2025-09-19 08:57:11.058012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afe4ee89133'
down_revision: Union[str, None] = '080cfe381209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RecentRuns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('archive_filename', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RecentRuns', schema=None) as batch_op:
        batch_op.drop_column('archive_filename')
        batch_op.drop_column('archive')

    # ### end Alembic commands ###
