"""made user_id unique in webpush notifications and use string 'None' for anon

Revision ID: a58b792e50eb
Revises: 2f7a4893cb4d
Create Date: 2025-06-16 12:57:39.351166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58b792e50eb'
down_revision: Union[str, None] = '2f7a4893cb4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_WebPushSubscriptions')
    with op.batch_alter_table('WebPushNotificationPreferences', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_WebPushNotificationPreferences_user_id'), ['user_id'])

    with op.batch_alter_table('WebPushSubscriptions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WebPushSubscriptions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('WebPushNotificationPreferences', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_WebPushNotificationPreferences_user_id'), type_='unique')
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.create_table('_alembic_tmp_WebPushSubscriptions',
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('endpoint', sa.VARCHAR(), nullable=False),
    sa.Column('auth', sa.VARCHAR(), nullable=False),
    sa.Column('p256dh', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
