"""added process_units to notification preferences

Revision ID: eecdca082f8b
Revises: a58b792e50eb
Create Date: 2025-06-16 13:25:55.245975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eecdca082f8b'
down_revision: Union[str, None] = 'a58b792e50eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WebPushNotificationPreferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_units', sa.JSON(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WebPushNotificationPreferences', schema=None) as batch_op:
        batch_op.drop_column('process_units')

    # ### end Alembic commands ###
