# because github actions are shit, we need to combine every workflow in one file in order to be able to have jobs depend correctly on other jobs

name: Combined Workflows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SHOULD_PUBLISH_IMAGE: ${{ github.ref == 'refs/heads/main' }}  
  NODE_VERSION: 22.11 # 22.12 has incompatibilities https://github.com/nodejs/node/issues/56155 https://github.com/tailwindlabs/tailwindcss/pull/15421 due to https://nodejs.org/en/blog/release/v22.12.0#requireesm-is-now-enabled-by-default

jobs:

  test_backend:
    name: Unittest ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        python-version: ["3.11"]
    steps:
      - name: Debug env
        run: env    
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Install OpenPectus (as editable)
        run: pip install -e '.[development]'
      - name: Lint with flake8
        run: |
          # use configuration from ./.flake8
          cd openpectus
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          #flake8 . --count --exit-zero --statistics
      - name: Lint with flake8 (warnings)
        if: runner.os == 'Linux'
        run: |
          # use configuration from ./.flake8
          cd openpectus
          if ! flake8 . --count --statistics; then
            echo "::warning::Flake8 Lint Warning"
          fi
      - name: Type check with pyright
        run: pyright
      - name: Test with unittest
        run: |
          cd openpectus
          python -m unittest
  
  validate_uods:
    name: Validate UODs in Closed-Pectus repository
    needs: [test_backend]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger validation of UODs in Closed-Pectus repository
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CLOSED_PECTUS_REPOSITORY_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Open-Pectus/Closed-Pectus/dispatches \
            -d '{"event_type":"dispatch-event"}'

  build_frontend:
    name: Build frontend
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'openpectus/frontend/package-lock.json'
      - name: npm ci, lint, build
        working-directory: "openpectus/frontend"
        run: |
          npm ci
          npm run lint
          npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: "openpectus/frontend/dist"

  package_dist:
    name: Build and Package
    runs-on: ubuntu-22.04
    needs: [build_frontend, test_backend]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install openpectus python dependencies
        run: python -m pip install --upgrade pip build
      - name: Download frontend dist into aggregator
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: openpectus/aggregator/frontend-dist
      - name: Add build number to build.json
        env:
          #Version: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
          git_sha: ${{ github.sha }}
          build_number: ${{ github.run_number }}/${{ github.run_attempt }}
        run: |
          echo "{\"build_number\": \"$build_number\", \"git_sha\": \"$git_sha\"}" > openpectus/build.json
          echo "Build number: $build_number"
      - name: Build Open Pectus with frontend dist (package openpectus-x.y.z.tar.gz)
        # build openpectus-x.y.z.tar.gz using version number defined in source (__version__ in __init__.py)
        run: python -m build --sdist -o openpectus/dist
      - name: Archive Open Pectus with frontend dist (version no.)
        uses: actions/upload-artifact@v4
        with:
          name: openpectus-dist-pypi
          path: openpectus/dist/*.tar.gz
      - name: Rename package to remove version number (openpectus.tar.gz)
        # rename package file openpectus-x.y.z.tar.gz to openpectus.tar.gz for a Dockerfile independent of version
        run: mv openpectus/dist/openpectus-*.tar.gz openpectus/dist/openpectus.tar.gz
      - name: Archive Open Pectus with frontend dist for Docker
        uses: actions/upload-artifact@v4
        with:
          name: openpectus-dist
          path: |
            openpectus/dist
            openpectus/Dockerfile

  pypi_publish:
    needs: [package_dist]
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    if: ${{ vars.SHOULD_PUBLISH_IMAGE }}
    environment:
      name: pypi
      url: https://pypi.org/p/open-pectus
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download openpectus-dist-pypi artifact
        uses: actions/download-artifact@v4
        with:
          name: openpectus-dist-pypi
          path: dist
#      - name: Publish package distributions to PyPI Test
#        if: github.ref != 'refs/heads/main'
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          repository-url: https://test.pypi.org/legacy/
      - name: Publish package distributions to PyPI
        if: github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@release/v1

  publish_docker_image:
    name: Publish Docker image
    needs: [package_dist]
    runs-on: ubuntu-latest
    if: ${{ vars.SHOULD_PUBLISH_IMAGE }}
    permissions:
      packages: write
      contents: read
    steps:
      - name: Download openpectus-dist artifact
        uses: actions/download-artifact@v4
        with:
          name: openpectus-dist
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            ${{ secrets.ACR_ENDPOINT }}/open-pectus
      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to Azure container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push container image to registries
        uses: docker/build-push-action@v5
        with:
          push: 'true'
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: .
          file: ./Dockerfile

  deploy_image:
    name: Deploy Docker image on Azure and Digital Ocean
    needs: [publish_docker_image]
    runs-on: ubuntu-latest
    if: ${{ vars.SHOULD_PUBLISH_IMAGE }}
    permissions:
      packages: write
      contents: read
    steps:
      # https://docs.digitalocean.com/reference/api/api-reference/#operation/apps_create_deployment
      - name: Trigger deployment in Digital Ocean after push to Github container registry
        run: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.DIGITALOCEAN_TOKEN }}" "https://api.digitalocean.com/v2/apps/${{ secrets.DIGITALOCEAN_APP_ID }}/deployments"
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACR_DEPLOY_CREDENTIALS }}
      - name: Deploy to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          dns-name-label: open-pectus-github
          resource-group: ${{ secrets.ACR_DEPLOY_RESOURCE_GROUP }}
          image: ${{ secrets.ACR_ENDPOINT }}/open-pectus:main
          registry-login-server: ${{ secrets.ACR_DEPLOY_LOGIN_SERVER }}
          registry-username: ${{ secrets.ACR_DEPLOY_USERNAME }}
          registry-password: ${{ secrets.ACR_DEPLOY_SECRET }}
          name: open-pectus-github
          environment-variables: AGGREGATOR_PORT=80
          location: 'west europe'
