# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Frontend

on:
  push:
    branches: [ "main", "jhk/31-build-frontend-with-github-actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'openpectus/frontend/package-lock.json'
    - name: npm ci, build
      working-directory: "openpectus/frontend"
      run: |
        npm ci
        npm run build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend dist folder
        path: "openpectus/frontend/dist"