name: Publish and Deploy

on:
  push:
    branches: [ "main", "85-build-docker-containers-serving-frontend-and-aggregator" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    needs: build_frontend, build_aggregator
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: aggregator
      - uses: actions/download-artifact@v3
        with:
          name: frontend-dist
          path: frontend-dist

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile
